from enum import Enum


class SortingTypes(Enum):
    RELEVANCE = "RELEVANCE"
    DISTANCE_LOW_TO_HIGH = "DISTANCE_LOW_TO_HIGH"
    DISTANCE_HIGH_TO_LOW = "DISTANCE_HIGH_TO_LOW"
    PRICE_LOW_TO_HIGH = "PRICE_LOW_TO_HIGH"
    PRICE_HIGH_TO_LOW = "PRICE_HIGH_TO_LOW"
